# Generated by Django 5.1.4 on 2026-06-30 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pipeline", "0001_initial"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelineinstance",
            name="task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pipeline_instance",
                to="tasks.task",
                verbose_name="关联任务",
            ),
        ),
    ]
