# Generated by Django 5.1.4 on 2026-07-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', '任务指派'), ('task_updated', '任务更新'), ('comment_added', '新增评论'), ('stage_changed', '阶段变更'), ('stage_completed', '阶段完成')], max_length=50, verbose_name='通知类型'),
        ),
    ]
