# Generated by Django 5.1.4 on 2026-07-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='fields',
            field=models.JSONField(blank=True, default=list, verbose_name='自定义字段'),
        ),
    ]
