# Generated by Django 5.1.4 on 2026-07-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='current_node',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='当前阶段节点'),
        ),
    ]
