# Generated by Django 5.1.4 on 2026-07-04 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetype',
            name='lifecycle_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='生命周期配置'),
        ),
        migrations.CreateModel(
            name='ResourceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=50, verbose_name='事件类型')),
                ('summary', models.TextField(blank=True, verbose_name='事件摘要')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='扩展详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='resources.resourceitem', verbose_name='所属资源')),
            ],
            options={
                'verbose_name': '资源事件日志',
                'verbose_name_plural': '资源事件日志',
                'db_table': 'resources_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
